### ISSUE TITLE
[FeatReq]  Change color of selected section

### ISSUE THREAD

**Issue by Sayamame-beans** [anatawa12/clekeyOVR#1]
## What is this idea?
If the section color changes when we select a section, it would be very easy to understand which one we are selecting.  
Even if the positions of the sticks are shown, I believe changing the color would be visually effective.

**Comment by anatawa12** [comment]
maybe an feat req of [anatawa12/clekeyVRC](https://github.com/clekeyVRC)?

**Comment by Sayamame-beans** [comment]
I posted it here because I think it can be used as an idea for this whole project (clekey).
Of course, you can close it if you don't intend to adopt it or if the design is different from clekeyVRC that I have tried.

**Comment by anatawa12** [comment]
This project is under development and I'm making clekeyOVR as OpenVR port of  clekeyVRC so currently, clekeyVRC is the best place for feat req. 
In the feature, this can be changed.
